version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command: tail -F anything
    volumes:
      - ./project:/code
    ports:
      - "8000:8000"
    depends_on:
      - db